# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9859621005d91acb4607511ea0329d6e8da00019455f620f4a6caec20eb65e2e2d3e7cc9aab0ee93095a0d509712a66ce010b625e56c3a122e1851f7e5912dc

test:
  secret_key_base: c6c87fe324d483a2a1b6ac5c9d95e44604f3b8370d307b92d3719784c9a1ad0915162020a10c9f9e17dbd1313640781b52ac995995feeae051e768198b8f4a6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
